version: '3.8'

services:
  speech-to-text-notesphere-manager:
    image: isdockero/speech-to-text-notesphere-manager:latest
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  speech-to-text-notesphere-processor:
    image: isdockero/speech-to-text-notesphere-processor:latest
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  app-network:
    driver: overlay
